create table if not exists public.bot_state (
  id integer primary key check (id = 1),
  is_active boolean not null default false,
  usdt_balance numeric not null default 10000,
  holdings jsonb not null default '{}'::jsonb,
  trade_history jsonb not null default '[]'::jsonb,
  settings jsonb not null default '{}'::jsonb,
  last_scan_timestamp timestamptz,
  updated_at timestamptz not null default now()
);

create table if not exists public.bot_logs (
  id bigint generated by default as identity primary key,
  timestamp timestamptz not null default now(),
  level text not null default 'info' check (level in ('info', 'warn', 'error')),
  message text not null,
  symbol text
);

create index if not exists bot_logs_timestamp_idx on public.bot_logs (timestamp desc);
create index if not exists bot_logs_symbol_idx on public.bot_logs (symbol);
